from dataclasses import dataclass


@dataclass
class TickerInfo:
    asset_code: list[str]
    url_type: str


cost_mapping = {
    "AF": TickerInfo(["AFLT"], ""),
    "AL": TickerInfo(["ALRS"], ""),
    "BR": TickerInfo(["BR"], ""),
    "Eu": TickerInfo(["EURRUBF"], "futures"),
    "EURRUBF": TickerInfo(["EURRUBF"], "futures"),
    "GAZPF": TickerInfo(["GAZP"], ""),
    "GL": TickerInfo(["GLDRUBF"], "futures"),
    "GK": TickerInfo(["GMKN"], ""),
    "GLDRUBF": TickerInfo(["GLDRUBF"], "futures"),
    "GZ": TickerInfo(["GAZP"], ""),
    "HS": TickerInfo(["2800"], ""),
    "HY": TickerInfo(["HYDR"], ""),
    "IMOEXF": TickerInfo(["IMOEXF"], "futures"),
    "LK": TickerInfo(["LKOH"], ""),
    "ME": TickerInfo(["MOEX"], ""),
    "MG": TickerInfo(["MAGN"], ""),
    "ML": TickerInfo(["VKCO"], ""),
    "MM": TickerInfo(["IMOEXF"], "futures"),
    "MN": TickerInfo(["MGNT"], ""),
    "MY": TickerInfo(["IMOEXCNY"], "index"),
    "NK": TickerInfo(["NVTK"], ""),
    "NM": TickerInfo(["NLMK"], ""),
    "RB": TickerInfo(["RGBI"], "index"),
    "RI": TickerInfo(["RTSI"], "index"),
    "RM": TickerInfo(["RTSI"], ""),
    "RN": TickerInfo(["ROSN"], ""),
    "SBERF": TickerInfo(["SBER"], ""),
    "Si": TickerInfo(["USDRUBF"], "futures"),
    "SN": TickerInfo(["SNGS"], ""),
    "SP": TickerInfo(["SBERP"], ""),
    "SR": TickerInfo(["SBER"], ""),
    "TT": TickerInfo(["TATN"], ""),
    "TN": TickerInfo(["T"], ""),
    "USDRUBF": TickerInfo(["USDRUBF"], "futures"),
    "VB": TickerInfo(["VTBR"], ""),
    "VI": TickerInfo(["RVI"], "index"),
    "X5": TickerInfo(["X5"], ""),
    "YD": TickerInfo(["YDEX"], ""),
    "W4": TickerInfo(["W4"], ""),
    "SLVRUB_TOM": TickerInfo(["SLVRUB_TOM"], "currency"),
    "SV": TickerInfo(["SLVRUB_TOM", "Si"], "custom"),
    "PT": TickerInfo(["..."], ""),
    "PD": TickerInfo(["..."], ""),
    "AU": TickerInfo(["..."], ""),
    "NG": TickerInfo(["..."], "futures"),
    "NA": TickerInfo(["..."], "futures"),
    "SF": TickerInfo(["..."], "futures"),
    "СС": TickerInfo(["..."], "futures"),
    "IB": TickerInfo(["..."], "futures"),
    "OJ": TickerInfo(["..."], "futures"),
    "CE": TickerInfo(["..."], "futures"),
    "FF": TickerInfo(["..."], "futures"),
    "KC": TickerInfo(["..."], "futures"),
    "BM": TickerInfo(["..."], "futures"),
    "NR": TickerInfo(["..."], "futures"),
    "DX": TickerInfo(["..."], "futures"),
    "MX": TickerInfo(["IMOEX"], "index"),
    "CNYRUBF": TickerInfo(["CNYRUB_TOM"], "currency"),
    "CR": TickerInfo(["CNYRUB_TOM"], "currency"),
    "ED": TickerInfo(["Eu", "Si"], "custom"),
    "GD": TickerInfo(["GL", "Si"], "custom"),
}
