from dataclasses import dataclass, field


@dataclass
class TickerInfo:
    asset_code: list[str]
    url_type: str
    cost_asset_code: list[str] = field(default_factory=list)


cost_mapping = {
    "AF": TickerInfo(["AFLT"], ""),
    "AL": TickerInfo(["ALRS"], ""),
    "BR": TickerInfo(["BR"], ""),
    "Eu": TickerInfo(["EURRUBF"], "futures"),
    "EURRUBF": TickerInfo(["EURRUBF"], "futures"),
    "GAZPF": TickerInfo(["GAZP"], ""),
    "UC": TickerInfo(["Si", "CR"], "custom"),
    "GL": TickerInfo(["GLDRUBF"], "futures"),
    "GK": TickerInfo(["GMKN"], ""),
    "GLDRUB_TOM": TickerInfo(["GLDRUB_TOM"], "currency"),
    "GLDRUBF": TickerInfo(["GLDRUBF"], "futures"),
    "GZ": TickerInfo(["GAZP"], ""),
    "HS": TickerInfo(["2800"], "index"),
    "HY": TickerInfo(["HYDR"], ""),
    "IMOEXF": TickerInfo(["IMOEXF"], "futures"),
    "LK": TickerInfo(["LKOH"], ""),
    "ME": TickerInfo(["MOEX"], ""),
    "MG": TickerInfo(["MAGN"], ""),
    "ML": TickerInfo(["VKCO"], ""),
    "MM": TickerInfo(["IMOEXF"], "futures"),
    "MN": TickerInfo(["MGNT"], ""),
    "MY": TickerInfo(["IMOEXCNY"], "index"),
    "NK": TickerInfo(["NVTK"], ""),
    "NM": TickerInfo(["NLMK"], ""),
    "RB": TickerInfo(["RGBI"], "index"),
    "RI": TickerInfo(["RTSI"], "index"),
    "RN": TickerInfo(["ROSN"], ""),
    "SBERF": TickerInfo(["SBER"], ""),
    "Si": TickerInfo(["USDRUBF"], "futures"),
    "SN": TickerInfo(["SNGS"], ""),
    "SP": TickerInfo(["SBERP"], ""),
    "SR": TickerInfo(["SBER"], ""),
    "TT": TickerInfo(["TATN"], ""),
    "TN": TickerInfo(["T"], ""),
    "USDRUBF": TickerInfo(["USDRUBF"], "futures"),
    "VB": TickerInfo(["VTBR"], ""),
    "VI": TickerInfo(["RVI"], "index"),
    "X5": TickerInfo(["X5"], ""),
    "YD": TickerInfo(["YDEX"], ""),
    "W4": TickerInfo(["W4"], ""),
    "SLVRUB_TOM": TickerInfo(["SLVRUB_TOM"], "currency"),
    "SV": TickerInfo(["SLVRUB_TOM", "Si"], "custom"),
    "PT": TickerInfo(["PLTRUB_TOM", "Si"], "custom"),
    "PD": TickerInfo(["PLDRUB_TOM", "Si"], "custom"),
    "AU": TickerInfo(["..."], ""),
    "NG": TickerInfo(["..."], "futures"),
    "NA": TickerInfo(["..."], "futures"),
    "SF": TickerInfo(["..."], "futures"),
    "CC": TickerInfo(["..."], "futures"),
    "IB": TickerInfo(["..."], "futures"),
    "OJ": TickerInfo(["..."], "futures"),
    "CE": TickerInfo(["..."], "futures"),
    "FF": TickerInfo(["..."], "futures"),
    "KC": TickerInfo(["..."], "futures"),
    "BM": TickerInfo(["..."], "futures"),
    "NR": TickerInfo(["..."], "futures"),
    "DX": TickerInfo(["..."], "futures"),
    "MX": TickerInfo(["IMOEX"], "index"),
    "CNYRUBF": TickerInfo(["CNYRUB_TOM"], "currency"),
    "CR": TickerInfo(["CNYRUB_TOM"], "currency"),
    "ED": TickerInfo(["Eu", "Si"], "custom"),
    "GD": TickerInfo(["GL", "Si"], "custom"),
    "RM": TickerInfo(["RTSI"], "index"),
    "PLTRUB_TOM": TickerInfo(["PLTRUB_TOM"], "currency"),
    "PLDRUB_TOM": TickerInfo(["PLDRUB_TOM"], "currency"),
    "РТС": TickerInfo(["RI", "RM"], "synthetic", ["RTSI"]),
    "SCNYR": TickerInfo(["CR", "CNYRUBF"], "synthetic", ["CNYRUB_TOM"]),
    "SUSDR": TickerInfo(["Si", "USDRUBF"], "synthetic", ["USDRUBF"]),
    "SEURR": TickerInfo(["Eu", "EURRUBF"], "synthetic", ["EURRUBF"]),
    "SMOEX": TickerInfo(["MX", "MM", "IMOEXF"], "synthetic", ["IMOEXF"]),
    "RTSI": TickerInfo(["RTSI"], "index"),
    "CNYRUB_TOM": TickerInfo(["CNYRUB_TOM"], "currency")
}
